pipeline {
    agent any

    environment {
        IMAGE_NAME = 'demo-ci-cd'
        IMAGE_TAG = "build-${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                    set -eux

                    python3 -m venv venv
                    . venv/bin/activate

                    python -m pip install --upgrade pip
                    pip install -r ci-cd/requirements.txt
                '''
            }
        }

        stage('Unit Test') {
            steps {
                sh '''
                    set -eux

                    . venv/bin/activate
                    pytest -v ci-cd/app --junitxml=test-results.xml
                '''
            }

            post {
                always {
                    junit 'test-results.xml'
                }
            }
        }

        stage('Check Docker') {
            steps {
                sh '''
                    set -eux

                    docker --version
                    docker info
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('ci-cd'){
                    sh '''
                        set -eux

                        echo "Building image:"
                        echo "${IMAGE_NAME}:${IMAGE_TAG}"

                        docker build \
                            -t "${IMAGE_NAME}:${IMAGE_TAG}" \
                            -t "${IMAGE_NAME}:latest" \
                            .
                    '''
                }
            }
        }

        stage('Run Container') {
            steps {
                dir ('ci-cd'){
                    sh '''
                        docker rm -rf demo-app || true
                        docker run -d \
                            --name demo-app \
                            -p 5000:5000 \
                            ${IMAGE_NAME}:${IMAGE_TAG}
                        sleep 3
                    '''
                }
            }
        }

        stage ("Smoke Test"){
            steps {
                sh '''
                    curl -f http://10.40.181.48:5000/health
                '''
            }
        }
        stage('Quality Checks') {
            parallel {
                stage('Unit Test') {
                    steps {
                        sh '''
                            . venv/bin/activate
                            pytest -v ci-cd/app
                        '''
                    }
                }

                stage('Check Python Syntax') {
                    steps {
                        sh '''
                            python3 -m py_compile ci-cd/app/main.py
                            python3 -m py_compile ci-cd/app/test_main.py
                        '''
                    }
                }

                stage('Check Files') {
                    steps {
                        sh '''
                            test -f ci-cd/Dockerfile
                            test -f ci-cd/requirements.txt
                        '''
                    }
                }
            }
        }
        stage ("Approval"){ 
            steps {
                timeout(time: 10, unit: 'MINUTES') {
                    input(
                        message: 'Deploy to production?',
                        ok: 'Deploy'
                    )
                }
            }
        }
        stage('Create Artifact') {
            steps {
                sh '''
                    mkdir -p dist
                    echo "Application build ${BUILD_NUMBER}" > dist/build-info.txt
                    tar -czf dist/demo-ci-cd.tar.gz ci-cd/app ci-cd/requirements.txt
                '''
            }

            post {
                success {
                    archiveArtifacts artifacts: 'dist/**', fingerprint: true
                }
            }
        }
    }

    post {
        success {
            echo "Pipeline succeeded"
        }

        failure {
            echo "Pipeline failed"
        }

        always {
            sh 'docker rm -f demo-app || true'
        }
    }
}