pipeline{
    agent any
    stages {
        stage('Hello'){
            steps {
                echo "Hello Jenkins"
            }
        }

        stage("System Info"){
            steps {
                sh 'pwd'
                sh 'whoami'
                sh 'git --version'
            }
        }
        
        stage("Finish"){
            steps {
                echo 'Pipeline finished'
            }
        }
    }
}